version: "3.8"

services:
  todo:
    build: .
    container_name: todos
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo:/app
    ports:
      - "8000:8000"
    environment:
      - name=value