# Generated by Django 3.2.25 on 2024-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
